-- Even Fibonacci numbers
--
-- Each new term in the Fibonacci sequence is generated by adding the previous
-- two terms. By starting with 1 and 2, the first 10 terms will be:
--          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not
-- exceed four million, find the sum of the even-valued terms.

nthFibonacci :: Int -> Int
nthFibonacci = (map fib [0..] !!)
  where fib 0 = 0
        fib 1 = 1
        fib n = nthFibonacci (n - 2) + nthFibonacci (n - 1)

fibSum :: Int
fibSum = sum $ takeWhile (<= limit) evenFibs
  where evenFibs = filter even (map nthFibonacci [0..])
        limit = 4000000

main = putStrLn $ show fibSum

