/* Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */


#include <stdio.h>

#define LIMIT 4000000


int
even_fibs_sum()
{
	int y = 1;
	int x = 0;
	int z = 0;
	int sum = 0;

	while (y <= LIMIT) {
		if (y % 2 == 0) {
			sum += y;
		}

		z = x + y;
		x = y;
		y = z;
	}

	return sum;
}


int
main(int argc, char **argv)
{
	printf("The sum is %d.\n", even_fibs_sum());
	return 0;
}
